INSERT INTO houses (
    id,
    deleted,
    created_by,
    created_date,
    updated_by,
    updated_date,
    version,
    name,
    house_code,
    house_status,
    location,
    remark,
    total_rooms,
    available_rooms
) VALUES
      (
          uuid_generate_v4(),
          FALSE,
          'system',
          NOW(),
          NULL,
          NULL,
          0,
          'Sunrise Residence',
          'HOUSE-001',
          'ACTIVE',
          'Kuala Lumpur',
          'Near city center',
          0,
          0
      ),
      (
          uuid_generate_v4(),
          FALSE,
          'system',
          NOW(),
          NULL,
          NULL,
          0,
          'Green Valley House',
          'HOUSE-002',
          'ACTIVE',
          'Petaling Jaya',
          'Quiet residential area',
          0,
          0
      ),
      (
          uuid_generate_v4(),
          FALSE,
          'system',
          NOW(),
          NULL,
          NULL,
          0,
          'Ocean View Villa',
          'HOUSE-003',
          'ACTIVE',
          'Penang',
          'Sea-facing rooms',
          0,
          0
      ),
      (
          uuid_generate_v4(),
          FALSE,
          'system',
          NOW(),
          NULL,
          NULL,
          0,
          'Hilltop Residency',
          'HOUSE-004',
          'ACTIVE',
          'Genting Highlands',
          'Cool climate and scenic view',
          0,
          0
      );
