# application.yml
  spring:
    application:
      name: the-niche-colivin-application

#    datasource:
#      url: jdbc:h2:mem:testdb
#      driver-class-name: org.h2.Driver
#      username: sa
#      password: password
    datasource:
        url: jdbc:postgresql://localhost:5432/thenichedb_prd
        username: the_niche_app
        password: the_niche_11223344556677
        driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

    h2:
      console:
        enabled: true
        path: /h2-console

    # Validation settings
    mvc:
      throw-exception-if-no-handler-found: true
    web:
      resources:
        add-mappings: false

  logging:
    level:
      com.myapp: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  server:
    port: 8080
    error:
      include-message: always
      include-binding-errors: always

  # Custom application properties
  app:
    pagination:
      default-page-size: 20
      max-page-size: 100
